language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

sudo: false

addons:
  apt:
    packages:
      - nginx

env:
  - BEHAT_VERSION="3.0.*"
  - BEHAT_VERSION="3.1.*"
  - BEHAT_VERSION="3.2.*"
  - BEHAT_VERSION="3.3.*"
  - BEHAT_VERSION="3.4.*"

before_install:
  # start a web server on port 8081, running in the background
  - bin/start_server.sh

install:
  - composer require behat/behat:${BEHAT_VERSION}
  - if [ $(phpenv version-name) == "7.2" ]; then composer install --no-interaction --prefer-source; else composer install --no-interaction --prefer-source --no-dev; fi
  - composer show -i
  - vendor/bin/behat --version

script:
  - vendor/bin/behat
  - if [ $(phpenv version-name) == "7.2" ]; then ./vendor/bin/phpcs -v --standard=ruleset.xml features src www; fi
