language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

services:
  - docker

env:
  - BEHAT_VERSION="3.0.*"
  - BEHAT_VERSION="3.1.*"
  - BEHAT_VERSION="3.2.*"
  - BEHAT_VERSION="3.3.*"

before_install:
  - touch www/employees.json && chmod 777 www/employees.json
  - docker-compose up -d
  - docker ps -a

install:
  - composer require behat/behat:${BEHAT_VERSION}
  - if [ $(phpenv version-name) == "7.2" ]; then composer install --no-interaction --prefer-source; else composer install --no-interaction --prefer-source --no-dev; fi
  - composer show -i
  - vendor/bin/behat --version

script:
  - vendor/bin/behat
  - if [ $(phpenv version-name) == "7.2" ]; then ./vendor/bin/phpcs -v --standard=ruleset.xml features src www; fi
