version: '3'

services:
    web:
        image: richarvey/nginx-php-fpm:latest
        working_dir: "/var/www/html"
        ports:
            - "80:80"
        volumes:
            - ./nginx-site.conf:/etc/nginx/sites-available/default.conf
            - ./www:/var/www/html
